version: '3'
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"